image: node:alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm

stages:
  - test

before_script:
  - yarn ci

jest-tests:
  stage: test
  script:
    - yarn jest --ci

lint-tests:
  stage: test
  script:
    - yarn lint
